name: Release

on:
  push:
    tags:
      - '*'

env:
  binary: rofi_edit


jobs:
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-gnu
      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install libcogl-pango-dev
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/release/lib${{ env.binary }}.so
          asset_name: lib${{ env.binary }}.so
          tag: ${{ github.ref }}
          overwrite: true
